### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'status')

### ISSUE THREAD

**Issue by smikula** [jgolla/torn-api#374]
I'm hitting this error periodically, looks like it happens when there is an error with the response and for some reason `error.response` is undefined.

```
TypeError: Cannot read properties of undefined (reading 'status')
    at C:\home\site\wwwroot\node_modules\ts-torn-api\dist\index.js:65:60
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Torn.apiQueryToArray (C:\home\site\wwwroot\node_modules\ts-torn-api\dist\TornAPIBase.js:43:26)
```

**Comment by jgolla** [comment]
That is a weird one. This looks like its coming from the inceptor, but I can't figure out why it would be empty. I'm going to add some error checks around the response and return a 500 if this happens.

```
        // Add a response interceptor
        axios.interceptors.response.use(response => {
            // Any status code that lie within the range of 2xx cause this function to trigger
            // just pass thru
            return response;
        }, error => {
            // Any status codes that falls outside the range of 2xx cause this function to trigger
            // return in the form of ITornApiError
            if(error.response) {
                return { data: { error: { code: error.response.status, error: error.response.statusText } } };
            } else {
                // protect against no repsonse being returned
                return { data: { error: { code: 500, error: 'Unknown error occurred.' } } };
            }
        });
```

**Comment by smikula** [comment]
Thanks for the quick fix!
